### ISSUE TITLE
Color map dots according to ...

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#107]
Perhaps color the dots on the map according to signal strength. And put
the legend in Settings or somewhere, so as not to crowd the map. Or have
it (plus the rest of the settings) accessible via a "?" somewhere on the
map.

(Of course this opens a Pandora's Box. Other users will want the dots colored according to Cell ID. Even others according to LAC, etc. OK, have a setting to choose what item to color by.)

**Comment by zamojski** [comment]
I will provide a legend describing the color coding of the dots. I think that introducing more colors may lead to difficulties in understanding what is presented on the map. It's also difficult to implement as each phone may return different signal strength range of values (due to stronger or weaker antenna) and the signal strength range varies between cell types.
