### ISSUE TITLE
Percentage shown again on uploading screen

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#186]
Here the two numbers just mean the same thing; 92% same as 92/100. maybe just show one version of them.
![Screenshot_20221010-220540_Tower Collector.jpg](https://user-images.githubusercontent.com/1230959/194981376-62a05525-0691-41d7-a6b3-15d6dbee04af.jpg)

**Comment by zamojski** [comment]
I've checked and the percentage is calculated and shown automatically one the range 0-100 is set. Here instead of 0-100 value I could use number of measurements exported / total to export, however there's no easy way to provide such detailed information here. Moreover there's no way to just leave one of these values visible on the screen.
