### ISSUE TITLE
Network Type button should always say something 

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#187]
Here, when not collecting, and even an airplane mode, I touched the words Network Type. Nothing happened. There should be at least a message saying what it's supposed to happen.
![Screenshot_20221103-114857_Tower Collector.jpg](https://user-images.githubusercontent.com/1230959/199783799-ead69a77-22b2-4d53-9134-ea94915f2422.jpg)

**Comment by zamojski** [comment]
I believe it's related to your phone - it cannot find the right setting screen in the system settings to open. This happens if phone manufacturer changes 'too much' against Android specification. I will check if there's anything we can improve here but nonetheless the action works regardless if collection is active.

**Comment by zamojski** [comment]
Please check if it works better in 2.14.4 available for everyone in couple of days.

**Comment by jidanni** [comment]
Okay, now I'm using that new version.

Okay, now when not collecting please do this:

Visit the map panel.

Now press the three buttons menu.

Now tap Network type.


The screen becomes entirely black for one second.

Then the map reappears.

That's all that happens.

It looks real weird.

**Comment by zamojski** [comment]
I cannot reproduce that on my phone and emulator.
