### ISSUE TITLE
Getting "Invalid system time" despite having automatic date and time enabled

### ISSUE THREAD

**Issue by Goldmaster** [zamojski/TowerCollector#201]
I get this message that says

`Your current system date and/or time is invalid comparing to GPS time. Measurements will be saved with correct time but presented statistics may be inaccurate. Please set the date and time in your device.`

But I know I have the correct time and date as automatic date and time is enabled in Samsung s10 phones settings. Why is this coming up? Does it effect contribution?

**Comment by zamojski** [comment]
Starting on November 3, 2019, mobile devices manufactured between 2006 and 2016 may have their GPS accuracy impacted due to GPS Rollover issue. I know your S10 is newer but maybe Samsung didn't fix that issue correctly.

The message is presented when there's 2 days (!) difference between system time and GPS time. If both values are incorrect then the app will refuse to collect any measurements. That means if the app collects measurements they will be saved with correct date and time. The contribution is not affected in that case.

**Comment by Goldmaster** [comment]
Closing this as the question has been well answered. Doesn't effect contributions
