### ISSUE TITLE
Retiring the Mozilla Location Service

### ISSUE THREAD

**Issue by KovalevArtem** [zamojski/TowerCollector#223]
Mozilla has announced a decision to close the MLS (Mozilla Location Service) project.

https://discourse.mozilla.org/t/retiring-the-mozilla-location-service/128693

https://github.com/mozilla/ichnaea/issues/2065

**Comment by nekohayo** [comment]
Could TowerCollector eventually become part of a solution to not only collect cell towers, but also WiFi SSIDs, if an eventual database/service surfaces as a replacement for MLS?

**Comment by zamojski** [comment]
> Could TowerCollector eventually become part of a solution to not only collect cell towers, but also WiFi SSIDs, if an eventual database/service surfaces as a replacement for MLS?

The option to collect WiFi was already requested #49

**Comment by jidanni** [comment]
Maybe instead of uploading to Mozilla, it can upload to https://www.cellmapper.net etc.

**Comment by zamojski** [comment]
cellmapper.net is not an open source project and doesn't have public API so definitely no support for this one.

**Comment by zamojski** [comment]
I think MLS upload could be replaced by wigle.net but I need to take a closer look at their licensing.

**Comment by holdit** [comment]
I assume more than one alternative will pop up, so it would be nice if the app could upload to more than just two services.

Let's say you add beaconDB. Since the support for "MLS compatible" services is there, we should be able to add a different server/service. Currently it's either MLS or a custom server, but we could upload to more than one MLS compatible service at the same time.

For other services that need their own format, that would be extra work of course - and obviously you can't support everything - but still, I think having one app contributing to many services could be useful.

**Comment by lucasmz-dev** [comment]
> I think MLS upload could be replaced by wigle.net but I need to take a closer look at their licensing.

I'm still lost on the usefulness of Wigle, like what's it used for, they seem a bit closed off
