### ISSUE TITLE
Everybody switch MLS uploads to BeaconDB

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#228]
Everybody should turn off MLS uploads in Preferences. 

Else the app will waste much time and data plan, only to give a failure message at the end.

**Comment by EchedelleLR** [comment]
I am unsure if you read https://github.com/zamojski/TowerCollector/issues/223 but BeaconDB exists as an alternative and TowerCollector already allows using custom MLS service.

Instead of encouraging no contributing, I would encourage changing the MLS service to BeaconDB using the app settings designed for that purpose.

**Comment by jidanni** [comment]
OK, I found the instructions, https://beacondb.net/ .

**Comment by breversa** [comment]
Will Tower Collector be updated to contribute to BeaconDB instead of MLS without user input (for those using the default setting, of course)? :)

I see no added value to:
1. Keep MLS as it's retired
2. NOT switch to a working alternative

**Comment by lucasmz-dev** [comment]
beacondb.net will most likely appreciate more awareness and contributors, giving it a little spotlight would be nice to make users aware, MLS is useless now, beacondb.net is meant to be much more resistant than MLS was, as there's supposed to be public dumps that are redacted for privacy that aren't just for cell networks but also Wi-Fi and Bluetooth.

Having a way to send data previously only sent to OpenCelliD would also be interesting

**Comment by stevenroose** [comment]
If/when this is changed, should probably explicitly indicate this by naming beacondb.
