### ISSUE TITLE
Allow overriding how many meters is considered accurate 

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#233]
![Screenshot_20240830_060345_Tower Collector.jpg](https://github.com/user-attachments/assets/f71fc075-55d5-423d-a48e-8ff1b45ebe55)

I would like to discuss today, how this number is chosen. In other words what is considered accurate. I have a suspicion that it is hardwired into the program. Perhaps 35 m. Well it's very bad to have something hardwired into the program that cannot be changed by a preference. 

Furthermore 35 m is rather old-fashioned in these days of 1 m precise cell phone gps's. 

Anyway I'm talking about the minimum number of meters before the bar changes into a blue bar.

Note that this is only slightly related to  #231.

**Comment by zamojski** [comment]
It's 40 meters and that value I consider good enough when traveling at high speed train or in crowded city areas where GPS isn't that precise. There must be a limit defined in the code to avoid pollution of database with useless measurements and situation where, due to poor GPS signal, you can infinitely collect measurements without even moving.

**Comment by zamojski** [comment]
Not planned,
