### ISSUE TITLE
Ability to send historical data to BeaconDB?

### ISSUE THREAD

**Issue by olekstomek** [zamojski/TowerCollector#240]
Will it be possible to send historical data (already collected previously) to BeaconDB?

**Comment by zamojski** [comment]
It depends 🙂 Tower Collector deletes local data after each upload and there's no way to recover it. However if you exported the measurements before each upload to CSV or JSON for MLS format you can use them to upload your data to a new source.

Anyway I don't know if this is necessary because BeaconDB already contains a large numbe of cell information, most likely from MLS. @joelkoen can you confirm what data is available in BeaconDB?

**Comment by olekstomek** [comment]
Thank for answer. So the only source for BeaconDB can be MLS or OpenCellID (of course I didn't make local copies of the generated files 🙂). Unless there is a way to export MLS or OpenCellId data from user account. On the other hand, old data (let's say older than one year) will not necessarily be useful.

**Comment by joelkoen** [comment]
I have imported cell tower data from MLS into BeaconDB as a fallback for responding to queries, as Mozilla was able to publish that information under the public domain. I have not however imported OpenCellID as it is licensed under CC BY SA 4.0 and I would like to publish BeaconDB's cell tower data in the future under CC0, just like MLS.

When I publish a cell tower data dump, clients can still make use of OpenCellID data as they can merge it with BeaconDB's data locally. Therefore I don't think historical data is too much of a concern (but thank you anyway haha!).

All the data shown on the map and used in the statistics is 100% BeaconDB - we're nearly at 500k cell towers!
