### ISSUE TITLE
use circle instead of triange on collect button

### ISSUE THREAD

**Issue by kolesar-andras** [zamojski/TowerCollector#5]
I think it's confusing that a triangle (play) button serves for recording data. A circle (record) button would be easier to understand.

**Comment by jidanni** [comment]
The square button/circle button is completely non-intuitive to me. Every time I see it I just can't remember which is which. What happens if YouTube decides to do this for their play button?

Okay, there should be a preference to configure this. Just like in  some countries people put the month in front of the day, and other countries people put the day in front of the month, so there should be some choice allowed here.

**Comment by zamojski** [comment]
So which icons do you suggest instead?

**Comment by jidanni** [comment]
The triangle of https://github.com/zamojski/TowerCollector/issues/64#issuecomment-515723016 
instead of circle for run.
