### ISSUE TITLE
wifi toggle feature request

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zamojski/TowerCollector#52]
Could you make the app to switch wifi on on new session start.

**Comment by c-e-p-x-u-o** [comment]
Oh, sorry, I thought it reports.

**Comment by zamojski** [comment]
If I find enough time it will start recording WiFi as well in 2019 :-)

**Comment by c-e-p-x-u-o** [comment]
OK, so this issue may be the feature request for future. Should it be reopened?

**Comment by zamojski** [comment]
I will link it with existing one - #49. Anyway I need to verify if turning WiFi on is necessary to scan wireless networks.

**Comment by Lee-Carre** [comment]
> I need to verify if turning WiFi on is necessary to scan wireless networks.

It isn't strictly necessary. However, in my experience, seems to work better when enabled. When disabled, it may be limited to only background scans.
When I'm out, collecting data, I enable it as habit, just to be sure.

Another important factor is if scan rate throttling is enabled or not (developer options toggle).

I'm not concerned by high scan rates (or other high power-usage), since I use and external battery.
