### ISSUE TITLE
upload button bad design

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [zamojski/TowerCollector#53]
This is a bad design:
![screenshot_20181230-122830_tower_collector](https://user-images.githubusercontent.com/14617699/50548663-740ed180-0c61-11e9-8ab6-f18df94f59b8.png)

The good design is to block (greyout) upload button to show user it's disabled.

You can leave popup explanation to clarify why it's exactly blocked.

**Comment by zamojski** [comment]
I will check if it's possible to display the explanation on disabled button.

**Comment by c-e-p-x-u-o** [comment]
Display the explanation on disabled button is optional.

Really it's better to make upload possible while recording.

**Comment by c-e-p-x-u-o** [comment]
One more thing related to bad design is that it's hard to distinguish "record" and "stop" stated.
On the one hand icons (cirgle and square) are good. On the other hand --- I often confuse.

**Comment by zamojski** [comment]
> Display the explanation on disabled button is optional.

This I would say is the must if the button is disabled.

> Really it's better to make upload possible while recording.

This makes internal logic extremely complicated and can cause data duplication and inconsistency. That's why I've blocked parallel modifications of database in version 1.3.0 in 2013.

The icons should express what action will be executed when you press it and "record" and "stop" icons are rather clean when you consider collecting only (it would be great to make them more expressive globally but I'm not a good graphic designer).

**Comment by zamojski** [comment]
> This makes internal logic extremely complicated and can cause data duplication and inconsistency. 

I'm not telling it's not possible, but the effort I need to put into such change will never pay back because it requires major changes in application architecture which I don't have time for.

> The good design is to block (greyout) upload button to show user it's disabled.

I've checked ant it doesn't seem possible to grey out the button without changing the icon manually (disabled button on Android toolbar looks exactly the same). The message will not appear as well so such button would look like broken.
