### ISSUE TITLE
Offer choice of compression

### ISSUE THREAD

**Issue by jidanni** [zamojski/TowerCollector#77]
One never ever expected that after checking the "Compress each exported file",
![Screenshot_20200530-165511](https://user-images.githubusercontent.com/1230959/83324253-906bcf00-a296-11ea-9e44-94a24cf942e4.jpg)
one would end up with .zip's and not .gz's !

https://nixcp.com/gzip-vs-zip-differences/ :
> ZIP is way more popular than .gz files in on Windows, Gzip on the other side is the standard file compression for Unix, Linux and Mac OS operating systems. 

> In general benchmarks, we’ve seen a big decrease in the size of a .gzip file over a normal compressed .zip file, so GZIP is way better if you want to save disk space in this case.

Anyway, do offer a radio button choice for what kind of compression we are going to get! Thanks.

**Comment by zamojski** [comment]
> One never ever expected that after checking the "Compress each exported file", one would end up with .zip's and not .gz's !

I would argue with that statement because zip is the most common compression format in the world, most likely due to popularity of Windows. One more argument for zip is that it's much easier to create such archive on Android, especially if you consider compression of multiple files in .tar.gz archive. I can provide the option to select the format in app preferences in one of future versions.
